# Стадия сборки
FROM node:20-alpine AS build

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все исходники
COPY . .

# Сборка проекта
RUN npm run build

# Стадия сервинга через nginx
FROM nginx:alpine

# Чистим дефолтный nginx
RUN rm -rf /usr/share/nginx/html/*

# Копируем собранную React админку
COPY --from=build /app/build/ /usr/share/nginx/html/

# Копируем конфиг nginx, если нужен кастомный
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Меняем права
RUN chown -R nginx:nginx /usr/share/nginx/html/ && \
    chmod -R 755 /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
