version = 5.0.0
archive_dir = /etc/letsencrypt/archive/pagel-digital.ru
cert = /etc/letsencrypt/live/pagel-digital.ru/cert.pem
privkey = /etc/letsencrypt/live/pagel-digital.ru/privkey.pem
chain = /etc/letsencrypt/live/pagel-digital.ru/chain.pem
fullchain = /etc/letsencrypt/live/pagel-digital.ru/fullchain.pem
[renewalparams]
account = d821c83b9eaae889094cdd4f81f321b1
authenticator = webroot
webroot_path = /usr/share/nginx/html,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
pagel-digital.ru = /usr/share/nginx/html
www.pagel-digital.ru = /usr/share/nginx/html
